//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenre
    {
        public int bgID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> genreID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
