//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookPublishers
    {
        public int bpID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> pubID { get; set; }
        public string authorName { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public string coverURL { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> pageNum { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
