//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUTUPHANEEntities1 : DbContext
    {
        public KUTUPHANEEntities1()
            : base("name=KUTUPHANEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookAuthors> BookAuthors { get; set; }
        public virtual DbSet<BookGenre> BookGenre { get; set; }
        public virtual DbSet<BookPublishers> BookPublishers { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<CartItems> CartItems { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<MemberAddress> MemberAddress { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
