//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchaseID { get; set; }
        public int memberID { get; set; }
        public int bookID { get; set; }
        public int quantity { get; set; }
        public decimal unitPrice { get; set; }
        public decimal totalPrice { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public string pName { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Members Members { get; set; }
    }
}
